package core;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.openqa.selenium.remote.BrowserType.CHROME;
import static org.openqa.selenium.remote.BrowserType.FIREFOX;

public class DriverFactory {
    private static WebDriver driver;
    public DriverFactory() {}

    public static WebDriver getDriver() {

        if(driver == null) {
            switch (ProjectProperties.browser) {
                case CHROME:
                    System.setProperty("webdriver.chrome.driver", "./src/test/resources/drivers/chromedriver.exe");
                    driver = new ChromeDriver();
                    break;
                case FIREFOX:
                    System.setProperty("webdriver.gecko.driver", "./src/test/resources/drivers/geckodriver.exe");
                    driver = new FirefoxDriver();
                    break;
            }
        }
        return driver;
    }

    /**
     * This method is to kill the proccess generated by Selenium.
     */
    public static void killDriver() {
        if(driver != null) {
            driver.quit();
            driver = null;
        }
    }

}
